### ISSUE TITLE
Update CSSfmt v0.7.0

### ISSUE THREAD

**Issue by morishitter** [dmnsgn/sublime-cssfmt#1]
Hi, I'm morishitter, author of CSSfmt.

CSSfmt v0.7.0 can read file from stdin, so I think, you need not to use `get-stding`.
Can you fix it?

Thanks!

**Comment by dmnsgn** [comment]
Hi. Fixed in release 2.0.0 by dd4041709047ff63673471f5036e292624acf0b8 which also remove the postcss dependency and do the same fix as your PR #2 .
Thanks.
