### ISSUE TITLE
Update CSSfmt

### ISSUE THREAD

**Issue by morishitter** [dmnsgn/sublime-cssfmt#3]
Hi, please update CSSfmt to v1.0.0.
Now, CSSfmt support formatting SCSS source code perfectly. https://github.com/morishitter/cssfmt/releases/tag/v1.0.0

Thanks.

**Comment by dmnsgn** [comment]
Hi, it throws an error with the version 5.0.2 of postcss: Node#_important was deprecated. Use Node#raws.important. 

Maybe this PR will solve that https://github.com/postcss/postcss/pull/515

Waiting for that to be fixed before updating.

**Comment by morishitter** [comment]
Thanks!

I think, all you have to do is updating cssfmt to v1.0.0 in `package.json` right?

**Comment by dmnsgn** [comment]
It is dependent on this issue being solved https://github.com/morishitter/cssfmt/issues/20. PostCSS author said it could come from an outdated plugin.

**Comment by morishitter** [comment]
I fixed it and released v1.0.1.

**Comment by dmnsgn** [comment]
Cool. Plugin updated to 1.0.1!
