### ISSUE TITLE
Error: unknown word

### ISSUE THREAD

**Issue by thegregthomp** [dmnsgn/sublime-cssfmt#4]
![image](https://cloud.githubusercontent.com/assets/1554124/9548402/48705a90-4d6e-11e5-8161-c22599ed6a81.png)

After install, restarted, checked node location.

**Comment by dmnsgn** [comment]
@thegregthomp could you copy/paste or create a gist of the file you launched the `Run CSSfmt` command against ?

**Comment by thegregthomp** [comment]
like.. the SASS file?

**Comment by thegregthomp** [comment]
https://gist.github.com/thegregthomp/ab6dca06accbdd035066

**Comment by thegregthomp** [comment]
@dmnsgn, thanks for the help BTW, timely response!

**Comment by dmnsgn** [comment]
Np. I downloaded the file and ran the command. Works fine for me on ST3. The error you are getting is not from the plugin itself but from a dependency.

Could you try to manually delete this folder `/Users/gthompson/Library/Application Support/Sublime Text 3/Packages/CSSfmt`, reopen Sublime and reinstall via the Package Manager ?

**Comment by thegregthomp** [comment]
Ok, so I did that, didn't work, got the same error. I started disabling packages, mainly around CSS/CSS3. I also disabled Git Gutter and Git Gutter Colors. After that it worked. Re-enabled them and it all works well. Weird but I think there was some conflict that appears resolved. I'll close the issue; hopefully this helps someone else. Thanks @dmnsgn
