### ISSUE TITLE
SCSS $var's are removed from border property shorthand.

### ISSUE THREAD

**Issue by atostudios** [dmnsgn/sublime-cssfmt#5]
Example:

border: 1px solid $color;

After running cssfmt;

border: 1px solid;

**Comment by dmnsgn** [comment]
Thanks for reporting this. I created a new issue on the main CSSfmt repository (because issues related to the CSSfmt core belong to the main repo): https://github.com/morishitter/cssfmt/issues/34

Closing this one as you can follow the progress on the other one.
