### ISSUE TITLE
run on save?

### ISSUE THREAD

**Issue by tj** [dmnsgn/sublime-cssfmt#6]
wondering if you know how to execute it on save, seems like sublime doesn't let you use super+s since it overrides saves

cheers

**Comment by dmnsgn** [comment]
I just added a sublime-settings file : https://github.com/dmnsgn/sublime-cssfmt#options in [release 2.2.0](https://github.com/dmnsgn/sublime-cssfmt/releases/tag/2.2.0) for `css`and `scss`files.

Basically:

*(Preferences > Package Settings > CSSfmt > Settings - User)*

```json
{
  "formatOnSave": true
}
```

Let me know if that works for you.

**Comment by tj** [comment]
Awesome, I see the defaults and added the user config but no luck with it triggering

**Comment by tj** [comment]
```
AttributeError: 'Window' object has no attribute 'extract_variables'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 185, in on_pre_save
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 184, in <lambda>
  File "./CSSfmt.py", line 60, in on_pre_save
AttributeError: 'Window' object has no attribute 'extract_variables'
Writing file /private/tmp/test.css with encoding UTF-8
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./CSSfmt.py", line 17, in run
AttributeError: 'Window' object has no attribute 'extract_variables'
```

**Comment by dmnsgn** [comment]
@tj which version of sublime do you have ?

**Comment by tj** [comment]
Just tried it on my other machine, this one is version 2.0.2 build 2221

**Comment by dmnsgn** [comment]
From the sublime download page:

> Build 3080
> API: Added Window.extract_variables()

I'll need to find a workaround.

**Comment by tj** [comment]
build 2221*, missing a digit haha. weird hmm I'll try updating, I had a lot of issues with 3.x before but it has been at least a year

**Comment by dmnsgn** [comment]
Just pushed a fix in 2.2.1 if you wanna give a try before updating.

**Comment by tj** [comment]
now it's:

```
error: CSSfmt
node_bridge() takes at least 3 arguments (2 given)
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./CSSfmt.py", line 28, in run
  File "./CSSfmt.py", line 44, in format
TypeError: node_bridge() takes at least 3 arguments (2 given)
Writing file /Users/tyler/dev/src/github.com/tj/tjholowaychuk/styles/exif.css with encoding UTF-8
```

**Comment by dmnsgn** [comment]
What about 2.2.2 ?

**Comment by tj** [comment]
boom! works, this will be awesome, thanks!

**Comment by dmnsgn** [comment]
Cool! This may be a bit slow with large files though.
